version: '3.7'

networks:
  elections: { }

x-common:
  &common
  build:
      context: .
      dockerfile: Dockerfile
  networks:
    - elections
  volumes:
    - .:/app
  restart: on-failure
  command: sh run_container.sh
  environment:
    &common-env
    HEARTBEAT_INTERVAL: 2000 
    ELECTION_TIMEOUT: 5000 
    ALGORITHM: raft

services:
  p1:
    <<: *common
    environment:
      <<: *common-env
      NODE_ID: 1
      NODE_TIMEOUT: 2500 

  p2:
    <<: *common
    environment:
      <<: *common-env
      NODE_ID: 2
      NODE_TIMEOUT: 2600 

  p3:
    <<: *common
    environment:
      <<: *common-env
      NODE_ID: 3
      NODE_TIMEOUT: 7000 
  
  p4:
    <<: *common
    environment:
      <<: *common-env
      NODE_ID: 4
      NODE_TIMEOUT: 9000 