version: '3.7'

networks:
  elections: { }

x-common:
  &common
  build:
      context: .
      dockerfile: Dockerfile
  networks:
    - elections
  volumes:
    - .:/app
  command: go run /app/main.go
  environment:
    &common-env
    PORT: 8000
    HEARTBEAT_TIME: 2 # seconds
    ELECTION_TIMEOUT: 5000 # ms

services:
  p1:
    <<: *common
    environment:
      <<: *common-env
      NODE_ID: 1
      NODE_TIMEOUT: 2500 # ms

  p2:
    <<: *common
    environment:
      <<: *common-env
      NODE_ID: 2
      NODE_TIMEOUT: 3000 # ms

  p3:
    <<: *common
    environment:
      <<: *common-env
      NODE_ID: 3
      NODE_TIMEOUT: 3500 # ms
  
  p4:
    <<: *common
    environment:
      <<: *common-env
      NODE_ID: 4
      NODE_TIMEOUT: 4000 # ms