version: '3.7'

networks:
  elections: { }

x-common:
  &common
  build:
      context: .
      dockerfile: Dockerfile
  networks:
    - elections
  volumes:
    - .:/app
  command: go run /app/main.go
  environment:
    &common-env
    PORT: 8000

services:
  p1:
    <<: *common
    environment:
      <<: *common-env
      NODE_ID: 1

  p2:
    <<: *common
    environment:
      <<: *common-env
      NODE_ID: 2

  p3:
    <<: *common
    environment:
      <<: *common-env
      NODE_ID: 3